/********************************************************************************
** Form generated from reading UI file 'ftm.ui'
**
** Created: Thu 6. Oct 14:02:56 2011
**      by: Qt User Interface Compiler version 4.7.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_FTM_H
#define UI_FTM_H

#include <QtCore/QLocale>
#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QDockWidget>
#include <QtGui/QDoubleSpinBox>
#include <QtGui/QGroupBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QListWidget>
#include <QtGui/QMainWindow>
#include <QtGui/QMenu>
#include <QtGui/QMenuBar>
#include <QtGui/QPushButton>
#include <QtGui/QRadioButton>
#include <QtGui/QScrollArea>
#include <QtGui/QSlider>
#include <QtGui/QSpinBox>
#include <QtGui/QStatusBar>
#include <QtGui/QTableWidget>
#include <QtGui/QToolBar>
#include <QtGui/QWidget>
#include <pintaFTUni.h>
#include "colorlabel.h"
#include "configclasi.h"
#include "ejeLinea.h"
#include "pantalla.h"
#include "pintaft.h"
#include "pintaftseg.h"

QT_BEGIN_NAMESPACE

class Ui_FTMClass
{
public:
    QAction *actionAbrir_PVM;
    QAction *actionMostrarBox;
    QAction *actionColorBox;
    QAction *actionMostrarFTM;
    QAction *actionDif_Centrales;
    QAction *actionKernels;
    QAction *actionPropiedades;
    QAction *actionPropiedadesVol;
    QAction *actionMoverIlu;
    QAction *actionPropiedadesIlu;
    QAction *actionActivarIlu;
    QAction *actionLaplaciano;
    QAction *actionGrad_del_Grad;
    QAction *actionM_Hessian;
    QAction *actionAbrir_FTs;
    QAction *actionAbrir_TexturasVol;
    QAction *actionGuardar_FTs;
    QAction *actionGuardar_TexturasVol;
    QAction *actionMostrar_WidgetFTM;
    QAction *actionMostrar_WidgetFTuni;
    QWidget *centralWidget;
    QMenuBar *menuBar;
    QMenu *menuArchivo;
    QMenu *menuEditar;
    QMenu *menuBox;
    QMenu *menuFTM;
    QMenu *menuFiltros;
    QMenu *menuTipo_Seg_Der;
    QMenu *menuVolumen;
    QMenu *menuIluminaci_n;
    QMenu *menuFT_Uni;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;
    QDockWidget *dockWidget_3;
    QWidget *dockWidgetFT;
    QGroupBox *ConFigClasi;
    conFigClasi *widgetSetFigClasi;
    QSlider *sliderConFigFin;
    QSlider *sliderConFigIni;
    colorLabel *pColorConf1;
    colorLabel *pColorConf2;
    QSlider *sliderAlphaFin;
    QSlider *sliderAlphaIni;
    QGroupBox *groupBox;
    QTableWidget *tablaFigClasi;
    QPushButton *crearFigClasi;
    QPushButton *eliminarFigClasi;
    QPushButton *subirFigClasi;
    QPushButton *bajarFigClasi;
    QPushButton *refrescarVol;
    QCheckBox *AutoRefresh;
    QGroupBox *groupBox_2;
    QScrollArea *scrollArea_2;
    pintaFTSeg *AreaDrawSeg;
    ejeLinea *EjeX2;
    ejeLinea *EjeZ;
    QScrollArea *scrollArea;
    pintaFT *AreaDraw;
    pantalla *pantallaWidget;
    ejeLinea *EjeY;
    ejeLinea *EjeX1;
    QLabel *cero;
    QLabel *cero_2;
    QPushButton *Push1D;
    QPushButton *Push2D;
    QPushButton *Push3D;
    QDockWidget *dockWidgetKernels;
    QWidget *dockWidgetContents;
    QPushButton *calculaKernels;
    QGroupBox *groupSegunda;
    QListWidget *listSegunda;
    QGroupBox *groupPrimera;
    QListWidget *listPrimera;
    QGroupBox *groupInterpola;
    QListWidget *listInterpola;
    QSpinBox *tamKernels;
    QLabel *label;
    QDockWidget *dockWidgetFT1;
    QWidget *dockWidgetContents_3;
    QGroupBox *groupBoxUni;
    QScrollArea *scrollArea_3;
    pintaFTUni *AreaDrawFT1;
    QPushButton *Push1DFTUni;
    QPushButton *Push2Do3DFTUni;
    QDockWidget *dockWidgetVol;
    QWidget *dockWidgetContents_2;
    QGroupBox *groupBoxVol;
    QLabel *labelTamVoxel;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *labelMuestreo;
    QSlider *sliderEscalaX;
    QSlider *sliderEscalaY;
    QSlider *sliderEscalaZ;
    QLineEdit *lineEditValor;
    QSpinBox *spinMinX;
    QSpinBox *spinMinY;
    QSpinBox *spinMinZ;
    QSpinBox *spinMaxX;
    QSpinBox *spinMaxY;
    QSpinBox *spinMaxZ;
    QDoubleSpinBox *doubleSpinMuestreo;
    QLabel *label_8;
    QLabel *x;
    QLabel *y;
    QLabel *z;
    QGroupBox *groupBoxFTMWidget;
    QSlider *sliderTruncaFTMWidget;
    QSpinBox *spinMaxFTMhisto2D;
    QSpinBox *spinMinFTMhisto2D;
    QLabel *labelActualValorHistoFTM;
    QSpinBox *spinActualFTMhisto2D;
    QDockWidget *dockWidgetIlumina;
    QWidget *dockWidgetContents_4;
    QGroupBox *groupIlumina;
    QRadioButton *radioGradiente;
    QRadioButton *radioSegDerivada;
    QRadioButton *radioMagYSeg;
    QRadioButton *radioBlinnPhong;
    QLabel *Lambiental;
    QLabel *Ldifusa;
    QLabel *Lespecular;
    QPushButton *pushAmbiental;
    QPushButton *pushDifusa;
    QPushButton *pushEspecular;
    QLabel *label_9;
    QDoubleSpinBox *doubleSpinShinIlumina;

    void setupUi(QMainWindow *FTMClass)
    {
        if (FTMClass->objectName().isEmpty())
            FTMClass->setObjectName(QString::fromUtf8("FTMClass"));
        FTMClass->resize(1231, 817);
        actionAbrir_PVM = new QAction(FTMClass);
        actionAbrir_PVM->setObjectName(QString::fromUtf8("actionAbrir_PVM"));
        actionAbrir_PVM->setEnabled(true);
        QIcon icon;
        icon.addFile(QString::fromUtf8("iconos/abrirVol.gif"), QSize(), QIcon::Normal, QIcon::Off);
        actionAbrir_PVM->setIcon(icon);
        actionMostrarBox = new QAction(FTMClass);
        actionMostrarBox->setObjectName(QString::fromUtf8("actionMostrarBox"));
        actionMostrarBox->setCheckable(true);
        QIcon icon1;
        icon1.addFile(QString::fromUtf8("iconos/mostrar.jpeg"), QSize(), QIcon::Normal, QIcon::Off);
        actionMostrarBox->setIcon(icon1);
        actionColorBox = new QAction(FTMClass);
        actionColorBox->setObjectName(QString::fromUtf8("actionColorBox"));
        QIcon icon2;
        icon2.addFile(QString::fromUtf8("iconos/color.jpeg"), QSize(), QIcon::Normal, QIcon::Off);
        actionColorBox->setIcon(icon2);
        actionMostrarFTM = new QAction(FTMClass);
        actionMostrarFTM->setObjectName(QString::fromUtf8("actionMostrarFTM"));
        actionMostrarFTM->setCheckable(true);
        actionDif_Centrales = new QAction(FTMClass);
        actionDif_Centrales->setObjectName(QString::fromUtf8("actionDif_Centrales"));
        actionDif_Centrales->setCheckable(true);
        actionDif_Centrales->setChecked(true);
        actionKernels = new QAction(FTMClass);
        actionKernels->setObjectName(QString::fromUtf8("actionKernels"));
        actionKernels->setCheckable(true);
        actionKernels->setEnabled(true);
        actionPropiedades = new QAction(FTMClass);
        actionPropiedades->setObjectName(QString::fromUtf8("actionPropiedades"));
        actionPropiedades->setEnabled(false);
        QIcon icon3;
        icon3.addFile(QString::fromUtf8("iconos/propiedades.gif"), QSize(), QIcon::Normal, QIcon::Off);
        actionPropiedades->setIcon(icon3);
        actionPropiedadesVol = new QAction(FTMClass);
        actionPropiedadesVol->setObjectName(QString::fromUtf8("actionPropiedadesVol"));
        actionPropiedadesVol->setIcon(icon3);
        actionMoverIlu = new QAction(FTMClass);
        actionMoverIlu->setObjectName(QString::fromUtf8("actionMoverIlu"));
        actionMoverIlu->setCheckable(true);
        QIcon icon4;
        icon4.addFile(QString::fromUtf8("iconos/mover.jpeg"), QSize(), QIcon::Normal, QIcon::Off);
        actionMoverIlu->setIcon(icon4);
        actionPropiedadesIlu = new QAction(FTMClass);
        actionPropiedadesIlu->setObjectName(QString::fromUtf8("actionPropiedadesIlu"));
        actionPropiedadesIlu->setIcon(icon3);
        actionActivarIlu = new QAction(FTMClass);
        actionActivarIlu->setObjectName(QString::fromUtf8("actionActivarIlu"));
        actionActivarIlu->setCheckable(true);
        actionLaplaciano = new QAction(FTMClass);
        actionLaplaciano->setObjectName(QString::fromUtf8("actionLaplaciano"));
        actionLaplaciano->setCheckable(true);
        actionGrad_del_Grad = new QAction(FTMClass);
        actionGrad_del_Grad->setObjectName(QString::fromUtf8("actionGrad_del_Grad"));
        actionGrad_del_Grad->setCheckable(true);
        actionGrad_del_Grad->setChecked(true);
        actionM_Hessian = new QAction(FTMClass);
        actionM_Hessian->setObjectName(QString::fromUtf8("actionM_Hessian"));
        actionM_Hessian->setCheckable(true);
        actionAbrir_FTs = new QAction(FTMClass);
        actionAbrir_FTs->setObjectName(QString::fromUtf8("actionAbrir_FTs"));
        QIcon icon5;
        icon5.addFile(QString::fromUtf8("iconos/abrirFT.gif"), QSize(), QIcon::Normal, QIcon::Off);
        actionAbrir_FTs->setIcon(icon5);
        actionAbrir_TexturasVol = new QAction(FTMClass);
        actionAbrir_TexturasVol->setObjectName(QString::fromUtf8("actionAbrir_TexturasVol"));
        QIcon icon6;
        icon6.addFile(QString::fromUtf8("iconos/abrirTexVol.gif"), QSize(), QIcon::Normal, QIcon::Off);
        actionAbrir_TexturasVol->setIcon(icon6);
        actionGuardar_FTs = new QAction(FTMClass);
        actionGuardar_FTs->setObjectName(QString::fromUtf8("actionGuardar_FTs"));
        actionGuardar_FTs->setCheckable(true);
        QIcon icon7;
        icon7.addFile(QString::fromUtf8("iconos/guardarFT.gif"), QSize(), QIcon::Normal, QIcon::Off);
        actionGuardar_FTs->setIcon(icon7);
        actionGuardar_TexturasVol = new QAction(FTMClass);
        actionGuardar_TexturasVol->setObjectName(QString::fromUtf8("actionGuardar_TexturasVol"));
        QIcon icon8;
        icon8.addFile(QString::fromUtf8("iconos/guardarTexVol.gif"), QSize(), QIcon::Normal, QIcon::Off);
        actionGuardar_TexturasVol->setIcon(icon8);
        actionMostrar_WidgetFTM = new QAction(FTMClass);
        actionMostrar_WidgetFTM->setObjectName(QString::fromUtf8("actionMostrar_WidgetFTM"));
        actionMostrar_WidgetFTM->setCheckable(true);
        actionMostrar_WidgetFTuni = new QAction(FTMClass);
        actionMostrar_WidgetFTuni->setObjectName(QString::fromUtf8("actionMostrar_WidgetFTuni"));
        actionMostrar_WidgetFTuni->setCheckable(true);
        centralWidget = new QWidget(FTMClass);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        FTMClass->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(FTMClass);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1231, 21));
        menuBar->setDefaultUp(false);
        menuArchivo = new QMenu(menuBar);
        menuArchivo->setObjectName(QString::fromUtf8("menuArchivo"));
        menuEditar = new QMenu(menuBar);
        menuEditar->setObjectName(QString::fromUtf8("menuEditar"));
        menuBox = new QMenu(menuEditar);
        menuBox->setObjectName(QString::fromUtf8("menuBox"));
        QIcon icon9;
        icon9.addFile(QString::fromUtf8("iconos/box.jpeg"), QSize(), QIcon::Normal, QIcon::Off);
        menuBox->setIcon(icon9);
        menuFTM = new QMenu(menuEditar);
        menuFTM->setObjectName(QString::fromUtf8("menuFTM"));
        QIcon icon10;
        icon10.addFile(QString::fromUtf8("iconos/FTMul.gif"), QSize(), QIcon::Normal, QIcon::Off);
        menuFTM->setIcon(icon10);
        menuFiltros = new QMenu(menuEditar);
        menuFiltros->setObjectName(QString::fromUtf8("menuFiltros"));
        QIcon icon11;
        icon11.addFile(QString::fromUtf8("iconos/filtro.gif"), QSize(), QIcon::Normal, QIcon::Off);
        menuFiltros->setIcon(icon11);
        menuTipo_Seg_Der = new QMenu(menuFiltros);
        menuTipo_Seg_Der->setObjectName(QString::fromUtf8("menuTipo_Seg_Der"));
        QIcon icon12;
        icon12.addFile(QString::fromUtf8("iconos/segundaDer.gif"), QSize(), QIcon::Normal, QIcon::Off);
        menuTipo_Seg_Der->setIcon(icon12);
        menuVolumen = new QMenu(menuEditar);
        menuVolumen->setObjectName(QString::fromUtf8("menuVolumen"));
        QIcon icon13;
        icon13.addFile(QString::fromUtf8("iconos/vol.gif"), QSize(), QIcon::Normal, QIcon::Off);
        menuVolumen->setIcon(icon13);
        menuIluminaci_n = new QMenu(menuEditar);
        menuIluminaci_n->setObjectName(QString::fromUtf8("menuIluminaci_n"));
        QIcon icon14;
        icon14.addFile(QString::fromUtf8("iconos/ilu.jpeg"), QSize(), QIcon::Normal, QIcon::Off);
        menuIluminaci_n->setIcon(icon14);
        menuFT_Uni = new QMenu(menuEditar);
        menuFT_Uni->setObjectName(QString::fromUtf8("menuFT_Uni"));
        QIcon icon15;
        icon15.addFile(QString::fromUtf8("iconos/FTUni.gif"), QSize(), QIcon::Normal, QIcon::Off);
        menuFT_Uni->setIcon(icon15);
        FTMClass->setMenuBar(menuBar);
        mainToolBar = new QToolBar(FTMClass);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        FTMClass->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(FTMClass);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        statusBar->setFocusPolicy(Qt::NoFocus);
        statusBar->setAutoFillBackground(false);
        statusBar->setSizeGripEnabled(true);
        FTMClass->setStatusBar(statusBar);
        dockWidget_3 = new QDockWidget(FTMClass);
        dockWidget_3->setObjectName(QString::fromUtf8("dockWidget_3"));
        dockWidget_3->setMinimumSize(QSize(300, 322));
        dockWidget_3->setStyleSheet(QString::fromUtf8("border-bottom-color: rgb(0, 0, 0);"));
        dockWidgetFT = new QWidget();
        dockWidgetFT->setObjectName(QString::fromUtf8("dockWidgetFT"));
        dockWidgetFT->setMinimumSize(QSize(300, 300));
        dockWidgetFT->setFocusPolicy(Qt::NoFocus);
        ConFigClasi = new QGroupBox(dockWidgetFT);
        ConFigClasi->setObjectName(QString::fromUtf8("ConFigClasi"));
        ConFigClasi->setGeometry(QRect(950, 0, 278, 301));
        ConFigClasi->setAutoFillBackground(true);
        widgetSetFigClasi = new conFigClasi(ConFigClasi);
        widgetSetFigClasi->setObjectName(QString::fromUtf8("widgetSetFigClasi"));
        widgetSetFigClasi->setGeometry(QRect(30, 50, 211, 241));
        widgetSetFigClasi->setAutoFillBackground(false);
        sliderConFigFin = new QSlider(ConFigClasi);
        sliderConFigFin->setObjectName(QString::fromUtf8("sliderConFigFin"));
        sliderConFigFin->setGeometry(QRect(30, 30, 211, 14));
        sliderConFigFin->setOrientation(Qt::Horizontal);
        sliderConFigIni = new QSlider(ConFigClasi);
        sliderConFigIni->setObjectName(QString::fromUtf8("sliderConFigIni"));
        sliderConFigIni->setGeometry(QRect(30, 20, 211, 14));
        sliderConFigIni->setSliderPosition(99);
        sliderConFigIni->setOrientation(Qt::Horizontal);
        sliderConFigIni->setInvertedAppearance(false);
        sliderConFigIni->setInvertedControls(false);
        pColorConf1 = new colorLabel(ConFigClasi);
        pColorConf1->setObjectName(QString::fromUtf8("pColorConf1"));
        pColorConf1->setGeometry(QRect(6, 20, 21, 30));
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush);
        pColorConf1->setPalette(palette);
        pColorConf1->setCursor(QCursor(Qt::PointingHandCursor));
        pColorConf1->setAutoFillBackground(true);
        pColorConf1->setFrameShape(QFrame::Box);
        pColorConf1->setAlignment(Qt::AlignCenter);
        pColorConf1->setMargin(1);
        pColorConf2 = new colorLabel(ConFigClasi);
        pColorConf2->setObjectName(QString::fromUtf8("pColorConf2"));
        pColorConf2->setGeometry(QRect(246, 20, 21, 30));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::Button, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush);
        pColorConf2->setPalette(palette1);
        pColorConf2->setCursor(QCursor(Qt::PointingHandCursor));
        pColorConf2->setAutoFillBackground(true);
        pColorConf2->setFrameShape(QFrame::Box);
        pColorConf2->setAlignment(Qt::AlignCenter);
        pColorConf2->setMargin(1);
        sliderAlphaFin = new QSlider(ConFigClasi);
        sliderAlphaFin->setObjectName(QString::fromUtf8("sliderAlphaFin"));
        sliderAlphaFin->setGeometry(QRect(10, 60, 14, 231));
        sliderAlphaFin->setMaximum(255);
        sliderAlphaFin->setOrientation(Qt::Vertical);
        sliderAlphaIni = new QSlider(ConFigClasi);
        sliderAlphaIni->setObjectName(QString::fromUtf8("sliderAlphaIni"));
        sliderAlphaIni->setGeometry(QRect(250, 60, 14, 231));
        sliderAlphaIni->setMaximum(255);
        sliderAlphaIni->setValue(255);
        sliderAlphaIni->setOrientation(Qt::Vertical);
        groupBox = new QGroupBox(dockWidgetFT);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(640, 0, 301, 301));
        tablaFigClasi = new QTableWidget(groupBox);
        if (tablaFigClasi->columnCount() < 3)
            tablaFigClasi->setColumnCount(3);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tablaFigClasi->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tablaFigClasi->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tablaFigClasi->setHorizontalHeaderItem(2, __qtablewidgetitem2);
        tablaFigClasi->setObjectName(QString::fromUtf8("tablaFigClasi"));
        tablaFigClasi->setGeometry(QRect(16, 32, 271, 241));
        tablaFigClasi->setLayoutDirection(Qt::LeftToRight);
        tablaFigClasi->setCornerButtonEnabled(true);
        tablaFigClasi->setColumnCount(3);
        tablaFigClasi->horizontalHeader()->setStretchLastSection(false);
        tablaFigClasi->verticalHeader()->setCascadingSectionResizes(false);
        tablaFigClasi->verticalHeader()->setDefaultSectionSize(20);
        tablaFigClasi->verticalHeader()->setHighlightSections(true);
        tablaFigClasi->verticalHeader()->setMinimumSectionSize(20);
        tablaFigClasi->verticalHeader()->setProperty("showSortIndicator", QVariant(false));
        crearFigClasi = new QPushButton(groupBox);
        crearFigClasi->setObjectName(QString::fromUtf8("crearFigClasi"));
        crearFigClasi->setGeometry(QRect(18, 272, 41, 25));
        QIcon icon16;
        icon16.addFile(QString::fromUtf8("iconos/crear_fig.gif"), QSize(), QIcon::Normal, QIcon::Off);
        crearFigClasi->setIcon(icon16);
        crearFigClasi->setIconSize(QSize(32, 32));
        eliminarFigClasi = new QPushButton(groupBox);
        eliminarFigClasi->setObjectName(QString::fromUtf8("eliminarFigClasi"));
        eliminarFigClasi->setGeometry(QRect(58, 272, 41, 25));
        QIcon icon17;
        icon17.addFile(QString::fromUtf8("iconos/eliminar_fig.gif"), QSize(), QIcon::Normal, QIcon::Off);
        eliminarFigClasi->setIcon(icon17);
        eliminarFigClasi->setIconSize(QSize(32, 32));
        subirFigClasi = new QPushButton(groupBox);
        subirFigClasi->setObjectName(QString::fromUtf8("subirFigClasi"));
        subirFigClasi->setGeometry(QRect(206, 10, 41, 21));
        QIcon icon18;
        icon18.addFile(QString::fromUtf8("iconos/hacia_arriba.gif"), QSize(), QIcon::Normal, QIcon::Off);
        subirFigClasi->setIcon(icon18);
        bajarFigClasi = new QPushButton(groupBox);
        bajarFigClasi->setObjectName(QString::fromUtf8("bajarFigClasi"));
        bajarFigClasi->setGeometry(QRect(246, 10, 41, 21));
        QIcon icon19;
        icon19.addFile(QString::fromUtf8("iconos/hacia_abajo.gif"), QSize(), QIcon::Normal, QIcon::Off);
        bajarFigClasi->setIcon(icon19);
        refrescarVol = new QPushButton(groupBox);
        refrescarVol->setObjectName(QString::fromUtf8("refrescarVol"));
        refrescarVol->setGeometry(QRect(70, 8, 24, 24));
        QIcon icon20;
        icon20.addFile(QString::fromUtf8("iconos/refrescar.jpeg"), QSize(), QIcon::Normal, QIcon::Off);
        refrescarVol->setIcon(icon20);
        refrescarVol->setCheckable(false);
        AutoRefresh = new QCheckBox(groupBox);
        AutoRefresh->setObjectName(QString::fromUtf8("AutoRefresh"));
        AutoRefresh->setGeometry(QRect(96, 12, 91, 17));
        groupBox_2 = new QGroupBox(dockWidgetFT);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(4, 0, 626, 301));
        scrollArea_2 = new QScrollArea(groupBox_2);
        scrollArea_2->setObjectName(QString::fromUtf8("scrollArea_2"));
        scrollArea_2->setGeometry(QRect(320, 30, 258, 258));
        scrollArea_2->setAutoFillBackground(true);
        scrollArea_2->setFrameShape(QFrame::Box);
        scrollArea_2->setFrameShadow(QFrame::Plain);
        scrollArea_2->setLineWidth(1);
        scrollArea_2->setMidLineWidth(0);
        scrollArea_2->setVerticalScrollBarPolicy(Qt::ScrollBarAsNeeded);
        scrollArea_2->setHorizontalScrollBarPolicy(Qt::ScrollBarAsNeeded);
        scrollArea_2->setWidgetResizable(true);
        AreaDrawSeg = new pintaFTSeg();
        AreaDrawSeg->setObjectName(QString::fromUtf8("AreaDrawSeg"));
        AreaDrawSeg->setGeometry(QRect(0, 0, 256, 256));
        QSizePolicy sizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(AreaDrawSeg->sizePolicy().hasHeightForWidth());
        AreaDrawSeg->setSizePolicy(sizePolicy);
        AreaDrawSeg->setAutoFillBackground(false);
        scrollArea_2->setWidget(AreaDrawSeg);
        EjeX2 = new ejeLinea(groupBox_2);
        EjeX2->setObjectName(QString::fromUtf8("EjeX2"));
        EjeX2->setGeometry(QRect(20, 290, 258, 7));
        EjeZ = new ejeLinea(groupBox_2);
        EjeZ->setObjectName(QString::fromUtf8("EjeZ"));
        EjeZ->setGeometry(QRect(310, 30, 7, 258));
        scrollArea = new QScrollArea(groupBox_2);
        scrollArea->setObjectName(QString::fromUtf8("scrollArea"));
        scrollArea->setGeometry(QRect(20, 30, 258, 258));
        scrollArea->setAutoFillBackground(true);
        scrollArea->setFrameShape(QFrame::Box);
        scrollArea->setFrameShadow(QFrame::Plain);
        scrollArea->setLineWidth(1);
        scrollArea->setMidLineWidth(0);
        scrollArea->setVerticalScrollBarPolicy(Qt::ScrollBarAsNeeded);
        scrollArea->setHorizontalScrollBarPolicy(Qt::ScrollBarAsNeeded);
        scrollArea->setWidgetResizable(true);
        AreaDraw = new pintaFT();
        AreaDraw->setObjectName(QString::fromUtf8("AreaDraw"));
        AreaDraw->setGeometry(QRect(0, 0, 256, 256));
        sizePolicy.setHeightForWidth(AreaDraw->sizePolicy().hasHeightForWidth());
        AreaDraw->setSizePolicy(sizePolicy);
        AreaDraw->setAutoFillBackground(false);
        pantallaWidget = new pantalla(AreaDraw);
        pantallaWidget->setObjectName(QString::fromUtf8("pantallaWidget"));
        pantallaWidget->setGeometry(QRect(20, -410, 600, 345));
        pantallaWidget->setLocale(QLocale(QLocale::Spanish, QLocale::Venezuela));
        scrollArea->setWidget(AreaDraw);
        EjeY = new ejeLinea(groupBox_2);
        EjeY->setObjectName(QString::fromUtf8("EjeY"));
        EjeY->setGeometry(QRect(10, 30, 7, 258));
        EjeX1 = new ejeLinea(groupBox_2);
        EjeX1->setObjectName(QString::fromUtf8("EjeX1"));
        EjeX1->setGeometry(QRect(320, 290, 258, 7));
        cero = new QLabel(groupBox_2);
        cero->setObjectName(QString::fromUtf8("cero"));
        cero->setGeometry(QRect(12, 286, 16, 16));
        cero_2 = new QLabel(groupBox_2);
        cero_2->setObjectName(QString::fromUtf8("cero_2"));
        cero_2->setGeometry(QRect(312, 286, 16, 16));
        Push1D = new QPushButton(groupBox_2);
        Push1D->setObjectName(QString::fromUtf8("Push1D"));
        Push1D->setGeometry(QRect(590, 30, 30, 30));
        Push2D = new QPushButton(groupBox_2);
        Push2D->setObjectName(QString::fromUtf8("Push2D"));
        Push2D->setGeometry(QRect(590, 58, 30, 30));
        Push3D = new QPushButton(groupBox_2);
        Push3D->setObjectName(QString::fromUtf8("Push3D"));
        Push3D->setEnabled(false);
        Push3D->setGeometry(QRect(590, 86, 30, 30));
        dockWidget_3->setWidget(dockWidgetFT);
        FTMClass->addDockWidget(static_cast<Qt::DockWidgetArea>(8), dockWidget_3);
        dockWidgetKernels = new QDockWidget(FTMClass);
        dockWidgetKernels->setObjectName(QString::fromUtf8("dockWidgetKernels"));
        dockWidgetKernels->setEnabled(true);
        dockWidgetContents = new QWidget();
        dockWidgetContents->setObjectName(QString::fromUtf8("dockWidgetContents"));
        calculaKernels = new QPushButton(dockWidgetContents);
        calculaKernels->setObjectName(QString::fromUtf8("calculaKernels"));
        calculaKernels->setGeometry(QRect(54, 274, 75, 23));
        groupSegunda = new QGroupBox(dockWidgetContents);
        groupSegunda->setObjectName(QString::fromUtf8("groupSegunda"));
        groupSegunda->setGeometry(QRect(120, 30, 60, 241));
        listSegunda = new QListWidget(groupSegunda);
        QListWidgetItem *__qlistwidgetitem = new QListWidgetItem(listSegunda);
        __qlistwidgetitem->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEditable|Qt::ItemIsDragEnabled|Qt::ItemIsUserCheckable|Qt::ItemIsEnabled);
        QListWidgetItem *__qlistwidgetitem1 = new QListWidgetItem(listSegunda);
        __qlistwidgetitem1->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEditable|Qt::ItemIsDragEnabled|Qt::ItemIsUserCheckable|Qt::ItemIsEnabled);
        QListWidgetItem *__qlistwidgetitem2 = new QListWidgetItem(listSegunda);
        __qlistwidgetitem2->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEditable|Qt::ItemIsDragEnabled|Qt::ItemIsUserCheckable|Qt::ItemIsEnabled);
        QListWidgetItem *__qlistwidgetitem3 = new QListWidgetItem(listSegunda);
        __qlistwidgetitem3->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEditable|Qt::ItemIsDragEnabled|Qt::ItemIsUserCheckable|Qt::ItemIsEnabled);
        QListWidgetItem *__qlistwidgetitem4 = new QListWidgetItem(listSegunda);
        __qlistwidgetitem4->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEditable|Qt::ItemIsDragEnabled|Qt::ItemIsUserCheckable|Qt::ItemIsEnabled);
        QListWidgetItem *__qlistwidgetitem5 = new QListWidgetItem(listSegunda);
        __qlistwidgetitem5->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEditable|Qt::ItemIsDragEnabled|Qt::ItemIsUserCheckable|Qt::ItemIsEnabled);
        QListWidgetItem *__qlistwidgetitem6 = new QListWidgetItem(listSegunda);
        __qlistwidgetitem6->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEditable|Qt::ItemIsDragEnabled|Qt::ItemIsUserCheckable|Qt::ItemIsEnabled);
        listSegunda->setObjectName(QString::fromUtf8("listSegunda"));
        listSegunda->setGeometry(QRect(9, 20, 42, 211));
        groupPrimera = new QGroupBox(dockWidgetContents);
        groupPrimera->setObjectName(QString::fromUtf8("groupPrimera"));
        groupPrimera->setGeometry(QRect(61, 30, 60, 241));
        listPrimera = new QListWidget(groupPrimera);
        QListWidgetItem *__qlistwidgetitem7 = new QListWidgetItem(listPrimera);
        __qlistwidgetitem7->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEditable|Qt::ItemIsDragEnabled|Qt::ItemIsUserCheckable|Qt::ItemIsEnabled);
        QListWidgetItem *__qlistwidgetitem8 = new QListWidgetItem(listPrimera);
        __qlistwidgetitem8->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEditable|Qt::ItemIsDragEnabled|Qt::ItemIsUserCheckable|Qt::ItemIsEnabled);
        QListWidgetItem *__qlistwidgetitem9 = new QListWidgetItem(listPrimera);
        __qlistwidgetitem9->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEditable|Qt::ItemIsDragEnabled|Qt::ItemIsUserCheckable|Qt::ItemIsEnabled);
        QListWidgetItem *__qlistwidgetitem10 = new QListWidgetItem(listPrimera);
        __qlistwidgetitem10->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEditable|Qt::ItemIsDragEnabled|Qt::ItemIsUserCheckable|Qt::ItemIsEnabled);
        QListWidgetItem *__qlistwidgetitem11 = new QListWidgetItem(listPrimera);
        __qlistwidgetitem11->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEditable|Qt::ItemIsDragEnabled|Qt::ItemIsUserCheckable|Qt::ItemIsEnabled);
        QListWidgetItem *__qlistwidgetitem12 = new QListWidgetItem(listPrimera);
        __qlistwidgetitem12->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEditable|Qt::ItemIsDragEnabled|Qt::ItemIsUserCheckable|Qt::ItemIsEnabled);
        QListWidgetItem *__qlistwidgetitem13 = new QListWidgetItem(listPrimera);
        __qlistwidgetitem13->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEditable|Qt::ItemIsDragEnabled|Qt::ItemIsUserCheckable|Qt::ItemIsEnabled);
        listPrimera->setObjectName(QString::fromUtf8("listPrimera"));
        listPrimera->setGeometry(QRect(9, 20, 42, 211));
        groupInterpola = new QGroupBox(dockWidgetContents);
        groupInterpola->setObjectName(QString::fromUtf8("groupInterpola"));
        groupInterpola->setGeometry(QRect(2, 30, 60, 241));
        listInterpola = new QListWidget(groupInterpola);
        QListWidgetItem *__qlistwidgetitem14 = new QListWidgetItem(listInterpola);
        __qlistwidgetitem14->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEditable|Qt::ItemIsDragEnabled|Qt::ItemIsUserCheckable|Qt::ItemIsEnabled);
        QListWidgetItem *__qlistwidgetitem15 = new QListWidgetItem(listInterpola);
        __qlistwidgetitem15->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEditable|Qt::ItemIsDragEnabled|Qt::ItemIsUserCheckable|Qt::ItemIsEnabled);
        QListWidgetItem *__qlistwidgetitem16 = new QListWidgetItem(listInterpola);
        __qlistwidgetitem16->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEditable|Qt::ItemIsDragEnabled|Qt::ItemIsUserCheckable|Qt::ItemIsEnabled);
        QListWidgetItem *__qlistwidgetitem17 = new QListWidgetItem(listInterpola);
        __qlistwidgetitem17->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEditable|Qt::ItemIsDragEnabled|Qt::ItemIsUserCheckable|Qt::ItemIsEnabled);
        QListWidgetItem *__qlistwidgetitem18 = new QListWidgetItem(listInterpola);
        __qlistwidgetitem18->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEditable|Qt::ItemIsDragEnabled|Qt::ItemIsUserCheckable|Qt::ItemIsEnabled);
        QListWidgetItem *__qlistwidgetitem19 = new QListWidgetItem(listInterpola);
        __qlistwidgetitem19->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEditable|Qt::ItemIsDragEnabled|Qt::ItemIsUserCheckable|Qt::ItemIsEnabled);
        QListWidgetItem *__qlistwidgetitem20 = new QListWidgetItem(listInterpola);
        __qlistwidgetitem20->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEditable|Qt::ItemIsDragEnabled|Qt::ItemIsUserCheckable|Qt::ItemIsEnabled);
        listInterpola->setObjectName(QString::fromUtf8("listInterpola"));
        listInterpola->setGeometry(QRect(9, 20, 42, 211));
        tamKernels = new QSpinBox(dockWidgetContents);
        tamKernels->setObjectName(QString::fromUtf8("tamKernels"));
        tamKernels->setGeometry(QRect(100, 4, 42, 22));
        tamKernels->setMinimum(3);
        tamKernels->setMaximum(11);
        tamKernels->setSingleStep(2);
        tamKernels->setValue(7);
        label = new QLabel(dockWidgetContents);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(60, 6, 41, 16));
        dockWidgetKernels->setWidget(dockWidgetContents);
        FTMClass->addDockWidget(static_cast<Qt::DockWidgetArea>(1), dockWidgetKernels);
        dockWidgetFT1 = new QDockWidget(FTMClass);
        dockWidgetFT1->setObjectName(QString::fromUtf8("dockWidgetFT1"));
        dockWidgetFT1->setAllowedAreas(Qt::LeftDockWidgetArea|Qt::RightDockWidgetArea);
        dockWidgetContents_3 = new QWidget();
        dockWidgetContents_3->setObjectName(QString::fromUtf8("dockWidgetContents_3"));
        groupBoxUni = new QGroupBox(dockWidgetContents_3);
        groupBoxUni->setObjectName(QString::fromUtf8("groupBoxUni"));
        groupBoxUni->setGeometry(QRect(0, 0, 281, 321));
        scrollArea_3 = new QScrollArea(groupBoxUni);
        scrollArea_3->setObjectName(QString::fromUtf8("scrollArea_3"));
        scrollArea_3->setGeometry(QRect(12, 20, 258, 258));
        scrollArea_3->setFrameShape(QFrame::Box);
        scrollArea_3->setFrameShadow(QFrame::Plain);
        scrollArea_3->setLineWidth(1);
        scrollArea_3->setMidLineWidth(0);
        scrollArea_3->setVerticalScrollBarPolicy(Qt::ScrollBarAsNeeded);
        scrollArea_3->setHorizontalScrollBarPolicy(Qt::ScrollBarAsNeeded);
        scrollArea_3->setWidgetResizable(true);
        AreaDrawFT1 = new pintaFTUni();
        AreaDrawFT1->setObjectName(QString::fromUtf8("AreaDrawFT1"));
        AreaDrawFT1->setGeometry(QRect(0, 0, 256, 256));
        sizePolicy.setHeightForWidth(AreaDrawFT1->sizePolicy().hasHeightForWidth());
        AreaDrawFT1->setSizePolicy(sizePolicy);
        scrollArea_3->setWidget(AreaDrawFT1);
        Push1DFTUni = new QPushButton(groupBoxUni);
        Push1DFTUni->setObjectName(QString::fromUtf8("Push1DFTUni"));
        Push1DFTUni->setGeometry(QRect(12, 280, 30, 30));
        Push2Do3DFTUni = new QPushButton(groupBoxUni);
        Push2Do3DFTUni->setObjectName(QString::fromUtf8("Push2Do3DFTUni"));
        Push2Do3DFTUni->setGeometry(QRect(41, 280, 41, 30));
        dockWidgetFT1->setWidget(dockWidgetContents_3);
        FTMClass->addDockWidget(static_cast<Qt::DockWidgetArea>(2), dockWidgetFT1);
        dockWidgetVol = new QDockWidget(FTMClass);
        dockWidgetVol->setObjectName(QString::fromUtf8("dockWidgetVol"));
        dockWidgetContents_2 = new QWidget();
        dockWidgetContents_2->setObjectName(QString::fromUtf8("dockWidgetContents_2"));
        groupBoxVol = new QGroupBox(dockWidgetContents_2);
        groupBoxVol->setObjectName(QString::fromUtf8("groupBoxVol"));
        groupBoxVol->setGeometry(QRect(0, -1, 281, 321));
        labelTamVoxel = new QLabel(groupBoxVol);
        labelTamVoxel->setObjectName(QString::fromUtf8("labelTamVoxel"));
        labelTamVoxel->setGeometry(QRect(20, 20, 81, 16));
        label_2 = new QLabel(groupBoxVol);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(22, 54, 46, 13));
        label_3 = new QLabel(groupBoxVol);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(22, 94, 46, 13));
        label_4 = new QLabel(groupBoxVol);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(22, 134, 46, 13));
        label_5 = new QLabel(groupBoxVol);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(162, 54, 46, 13));
        label_6 = new QLabel(groupBoxVol);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(162, 94, 46, 13));
        label_7 = new QLabel(groupBoxVol);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(162, 134, 46, 13));
        labelMuestreo = new QLabel(groupBoxVol);
        labelMuestreo->setObjectName(QString::fromUtf8("labelMuestreo"));
        labelMuestreo->setGeometry(QRect(20, 184, 101, 16));
        sliderEscalaX = new QSlider(groupBoxVol);
        sliderEscalaX->setObjectName(QString::fromUtf8("sliderEscalaX"));
        sliderEscalaX->setGeometry(QRect(30, 250, 241, 21));
        sliderEscalaX->setMinimum(0);
        sliderEscalaX->setValue(50);
        sliderEscalaX->setOrientation(Qt::Horizontal);
        sliderEscalaY = new QSlider(groupBoxVol);
        sliderEscalaY->setObjectName(QString::fromUtf8("sliderEscalaY"));
        sliderEscalaY->setGeometry(QRect(30, 270, 241, 21));
        sliderEscalaY->setMinimum(0);
        sliderEscalaY->setValue(50);
        sliderEscalaY->setOrientation(Qt::Horizontal);
        sliderEscalaZ = new QSlider(groupBoxVol);
        sliderEscalaZ->setObjectName(QString::fromUtf8("sliderEscalaZ"));
        sliderEscalaZ->setGeometry(QRect(30, 290, 241, 21));
        sliderEscalaZ->setMinimum(0);
        sliderEscalaZ->setValue(50);
        sliderEscalaZ->setOrientation(Qt::Horizontal);
        lineEditValor = new QLineEdit(groupBoxVol);
        lineEditValor->setObjectName(QString::fromUtf8("lineEditValor"));
        lineEditValor->setGeometry(QRect(100, 18, 71, 20));
        spinMinX = new QSpinBox(groupBoxVol);
        spinMinX->setObjectName(QString::fromUtf8("spinMinX"));
        spinMinX->setGeometry(QRect(58, 50, 61, 22));
        spinMinX->setMinimum(0);
        spinMinX->setMaximum(10000);
        spinMinX->setValue(1);
        spinMinY = new QSpinBox(groupBoxVol);
        spinMinY->setObjectName(QString::fromUtf8("spinMinY"));
        spinMinY->setGeometry(QRect(58, 90, 61, 22));
        spinMinY->setMaximum(10000);
        spinMinY->setValue(1);
        spinMinZ = new QSpinBox(groupBoxVol);
        spinMinZ->setObjectName(QString::fromUtf8("spinMinZ"));
        spinMinZ->setGeometry(QRect(58, 130, 61, 22));
        spinMinZ->setMaximum(10000);
        spinMinZ->setValue(1);
        spinMaxX = new QSpinBox(groupBoxVol);
        spinMaxX->setObjectName(QString::fromUtf8("spinMaxX"));
        spinMaxX->setGeometry(QRect(200, 50, 61, 22));
        spinMaxX->setMaximum(10000);
        spinMaxX->setValue(1);
        spinMaxY = new QSpinBox(groupBoxVol);
        spinMaxY->setObjectName(QString::fromUtf8("spinMaxY"));
        spinMaxY->setGeometry(QRect(200, 90, 61, 22));
        spinMaxY->setMaximum(10000);
        spinMaxY->setValue(1);
        spinMaxZ = new QSpinBox(groupBoxVol);
        spinMaxZ->setObjectName(QString::fromUtf8("spinMaxZ"));
        spinMaxZ->setGeometry(QRect(200, 130, 61, 22));
        spinMaxZ->setMaximum(10000);
        spinMaxZ->setValue(1);
        doubleSpinMuestreo = new QDoubleSpinBox(groupBoxVol);
        doubleSpinMuestreo->setObjectName(QString::fromUtf8("doubleSpinMuestreo"));
        doubleSpinMuestreo->setGeometry(QRect(118, 180, 121, 22));
        doubleSpinMuestreo->setDecimals(5);
        doubleSpinMuestreo->setMinimum(1e-05);
        doubleSpinMuestreo->setMaximum(1);
        doubleSpinMuestreo->setSingleStep(1e-05);
        doubleSpinMuestreo->setValue(0.05);
        label_8 = new QLabel(groupBoxVol);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(90, 220, 81, 16));
        x = new QLabel(groupBoxVol);
        x->setObjectName(QString::fromUtf8("x"));
        x->setGeometry(QRect(10, 250, 21, 16));
        y = new QLabel(groupBoxVol);
        y->setObjectName(QString::fromUtf8("y"));
        y->setGeometry(QRect(10, 270, 21, 16));
        z = new QLabel(groupBoxVol);
        z->setObjectName(QString::fromUtf8("z"));
        z->setGeometry(QRect(10, 290, 21, 16));
        groupBoxFTMWidget = new QGroupBox(dockWidgetContents_2);
        groupBoxFTMWidget->setObjectName(QString::fromUtf8("groupBoxFTMWidget"));
        groupBoxFTMWidget->setGeometry(QRect(0, 320, 281, 91));
        sliderTruncaFTMWidget = new QSlider(groupBoxFTMWidget);
        sliderTruncaFTMWidget->setObjectName(QString::fromUtf8("sliderTruncaFTMWidget"));
        sliderTruncaFTMWidget->setGeometry(QRect(10, 44, 264, 20));
        sliderTruncaFTMWidget->setMinimum(255);
        sliderTruncaFTMWidget->setMaximum(10000);
        sliderTruncaFTMWidget->setOrientation(Qt::Horizontal);
        spinMaxFTMhisto2D = new QSpinBox(groupBoxFTMWidget);
        spinMaxFTMhisto2D->setObjectName(QString::fromUtf8("spinMaxFTMhisto2D"));
        spinMaxFTMhisto2D->setGeometry(QRect(216, 16, 61, 22));
        spinMaxFTMhisto2D->setMinimum(255);
        spinMaxFTMhisto2D->setMaximum(2147483647);
        spinMaxFTMhisto2D->setValue(10000);
        spinMinFTMhisto2D = new QSpinBox(groupBoxFTMWidget);
        spinMinFTMhisto2D->setObjectName(QString::fromUtf8("spinMinFTMhisto2D"));
        spinMinFTMhisto2D->setGeometry(QRect(8, 16, 61, 22));
        spinMinFTMhisto2D->setMaximum(2147483647);
        spinMinFTMhisto2D->setValue(255);
        labelActualValorHistoFTM = new QLabel(groupBoxFTMWidget);
        labelActualValorHistoFTM->setObjectName(QString::fromUtf8("labelActualValorHistoFTM"));
        labelActualValorHistoFTM->setGeometry(QRect(90, 62, 91, 21));
        spinActualFTMhisto2D = new QSpinBox(groupBoxFTMWidget);
        spinActualFTMhisto2D->setObjectName(QString::fromUtf8("spinActualFTMhisto2D"));
        spinActualFTMhisto2D->setGeometry(QRect(146, 62, 61, 22));
        spinActualFTMhisto2D->setMinimum(255);
        spinActualFTMhisto2D->setMaximum(10000);
        dockWidgetVol->setWidget(dockWidgetContents_2);
        FTMClass->addDockWidget(static_cast<Qt::DockWidgetArea>(2), dockWidgetVol);
        dockWidgetIlumina = new QDockWidget(FTMClass);
        dockWidgetIlumina->setObjectName(QString::fromUtf8("dockWidgetIlumina"));
        dockWidgetContents_4 = new QWidget();
        dockWidgetContents_4->setObjectName(QString::fromUtf8("dockWidgetContents_4"));
        groupIlumina = new QGroupBox(dockWidgetContents_4);
        groupIlumina->setObjectName(QString::fromUtf8("groupIlumina"));
        groupIlumina->setGeometry(QRect(2, 0, 178, 195));
        radioGradiente = new QRadioButton(groupIlumina);
        radioGradiente->setObjectName(QString::fromUtf8("radioGradiente"));
        radioGradiente->setGeometry(QRect(10, 20, 111, 21));
        radioSegDerivada = new QRadioButton(groupIlumina);
        radioSegDerivada->setObjectName(QString::fromUtf8("radioSegDerivada"));
        radioSegDerivada->setGeometry(QRect(10, 40, 111, 21));
        radioMagYSeg = new QRadioButton(groupIlumina);
        radioMagYSeg->setObjectName(QString::fromUtf8("radioMagYSeg"));
        radioMagYSeg->setGeometry(QRect(10, 60, 151, 21));
        radioBlinnPhong = new QRadioButton(groupIlumina);
        radioBlinnPhong->setObjectName(QString::fromUtf8("radioBlinnPhong"));
        radioBlinnPhong->setGeometry(QRect(10, 80, 82, 17));
        Lambiental = new QLabel(groupIlumina);
        Lambiental->setObjectName(QString::fromUtf8("Lambiental"));
        Lambiental->setGeometry(QRect(3, 120, 51, 31));
        Lambiental->setAutoFillBackground(true);
        Lambiental->setFrameShape(QFrame::Box);
        Lambiental->setAlignment(Qt::AlignCenter);
        Ldifusa = new QLabel(groupIlumina);
        Ldifusa->setObjectName(QString::fromUtf8("Ldifusa"));
        Ldifusa->setGeometry(QRect(63, 120, 51, 31));
        Ldifusa->setAutoFillBackground(true);
        Ldifusa->setFrameShape(QFrame::Box);
        Ldifusa->setAlignment(Qt::AlignCenter);
        Lespecular = new QLabel(groupIlumina);
        Lespecular->setObjectName(QString::fromUtf8("Lespecular"));
        Lespecular->setGeometry(QRect(123, 120, 51, 31));
        Lespecular->setAutoFillBackground(true);
        Lespecular->setFrameShape(QFrame::Box);
        Lespecular->setAlignment(Qt::AlignCenter);
        pushAmbiental = new QPushButton(groupIlumina);
        pushAmbiental->setObjectName(QString::fromUtf8("pushAmbiental"));
        pushAmbiental->setGeometry(QRect(3, 150, 51, 14));
        pushAmbiental->setCheckable(false);
        pushAmbiental->setChecked(false);
        pushDifusa = new QPushButton(groupIlumina);
        pushDifusa->setObjectName(QString::fromUtf8("pushDifusa"));
        pushDifusa->setGeometry(QRect(63, 150, 51, 14));
        pushDifusa->setCheckable(false);
        pushDifusa->setChecked(false);
        pushEspecular = new QPushButton(groupIlumina);
        pushEspecular->setObjectName(QString::fromUtf8("pushEspecular"));
        pushEspecular->setGeometry(QRect(123, 150, 51, 14));
        pushEspecular->setCheckable(false);
        pushEspecular->setChecked(false);
        label_9 = new QLabel(groupIlumina);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(8, 170, 111, 16));
        doubleSpinShinIlumina = new QDoubleSpinBox(groupIlumina);
        doubleSpinShinIlumina->setObjectName(QString::fromUtf8("doubleSpinShinIlumina"));
        doubleSpinShinIlumina->setGeometry(QRect(110, 168, 62, 22));
        doubleSpinShinIlumina->setValue(20);
        dockWidgetIlumina->setWidget(dockWidgetContents_4);
        FTMClass->addDockWidget(static_cast<Qt::DockWidgetArea>(1), dockWidgetIlumina);

        menuBar->addAction(menuArchivo->menuAction());
        menuBar->addAction(menuEditar->menuAction());
        menuArchivo->addAction(actionAbrir_PVM);
        menuArchivo->addAction(actionAbrir_FTs);
        menuArchivo->addAction(actionAbrir_TexturasVol);
        menuArchivo->addSeparator();
        menuArchivo->addAction(actionGuardar_FTs);
        menuArchivo->addAction(actionGuardar_TexturasVol);
        menuEditar->addAction(menuFT_Uni->menuAction());
        menuEditar->addAction(menuFTM->menuAction());
        menuEditar->addAction(menuFiltros->menuAction());
        menuEditar->addAction(menuVolumen->menuAction());
        menuEditar->addAction(menuBox->menuAction());
        menuEditar->addAction(menuIluminaci_n->menuAction());
        menuBox->addAction(actionMostrarBox);
        menuBox->addAction(actionColorBox);
        menuFTM->addAction(actionMostrarFTM);
        menuFTM->addAction(actionMostrar_WidgetFTM);
        menuFiltros->addAction(menuTipo_Seg_Der->menuAction());
        menuFiltros->addAction(actionDif_Centrales);
        menuFiltros->addAction(actionKernels);
        menuFiltros->addAction(actionPropiedades);
        menuTipo_Seg_Der->addAction(actionLaplaciano);
        menuTipo_Seg_Der->addAction(actionGrad_del_Grad);
        menuTipo_Seg_Der->addAction(actionM_Hessian);
        menuVolumen->addAction(actionPropiedadesVol);
        menuIluminaci_n->addAction(actionActivarIlu);
        menuIluminaci_n->addAction(actionMoverIlu);
        menuIluminaci_n->addAction(actionPropiedadesIlu);
        menuFT_Uni->addAction(actionMostrar_WidgetFTuni);

        retranslateUi(FTMClass);

        QMetaObject::connectSlotsByName(FTMClass);
    } // setupUi

    void retranslateUi(QMainWindow *FTMClass)
    {
        FTMClass->setWindowTitle(QApplication::translate("FTMClass", "FTM", 0, QApplication::UnicodeUTF8));
        actionAbrir_PVM->setText(QApplication::translate("FTMClass", "Abrir PVM", 0, QApplication::UnicodeUTF8));
        actionMostrarBox->setText(QApplication::translate("FTMClass", "Mostrar", 0, QApplication::UnicodeUTF8));
        actionColorBox->setText(QApplication::translate("FTMClass", "Color", 0, QApplication::UnicodeUTF8));
        actionMostrarFTM->setText(QApplication::translate("FTMClass", "Mostrar 3D", 0, QApplication::UnicodeUTF8));
        actionDif_Centrales->setText(QApplication::translate("FTMClass", "Dif. Centrales", 0, QApplication::UnicodeUTF8));
        actionKernels->setText(QApplication::translate("FTMClass", "Kernels", 0, QApplication::UnicodeUTF8));
        actionPropiedades->setText(QApplication::translate("FTMClass", "Propiedades", 0, QApplication::UnicodeUTF8));
        actionPropiedadesVol->setText(QApplication::translate("FTMClass", "Propiedades", 0, QApplication::UnicodeUTF8));
        actionMoverIlu->setText(QApplication::translate("FTMClass", "Mover", 0, QApplication::UnicodeUTF8));
        actionPropiedadesIlu->setText(QApplication::translate("FTMClass", "Propiedades", 0, QApplication::UnicodeUTF8));
        actionActivarIlu->setText(QApplication::translate("FTMClass", "Activar", 0, QApplication::UnicodeUTF8));
        actionLaplaciano->setText(QApplication::translate("FTMClass", "Laplaciano", 0, QApplication::UnicodeUTF8));
        actionGrad_del_Grad->setText(QApplication::translate("FTMClass", "Grad. del Grad.", 0, QApplication::UnicodeUTF8));
        actionM_Hessian->setText(QApplication::translate("FTMClass", "M. Hessian", 0, QApplication::UnicodeUTF8));
        actionAbrir_FTs->setText(QApplication::translate("FTMClass", "Abrir FTs", 0, QApplication::UnicodeUTF8));
        actionAbrir_TexturasVol->setText(QApplication::translate("FTMClass", "Abrir TexturasVol", 0, QApplication::UnicodeUTF8));
        actionGuardar_FTs->setText(QApplication::translate("FTMClass", "Guardar FTs", 0, QApplication::UnicodeUTF8));
        actionGuardar_TexturasVol->setText(QApplication::translate("FTMClass", "Guardar TexturasVol", 0, QApplication::UnicodeUTF8));
        actionMostrar_WidgetFTM->setText(QApplication::translate("FTMClass", "Mostrar Widget", 0, QApplication::UnicodeUTF8));
        actionMostrar_WidgetFTuni->setText(QApplication::translate("FTMClass", "Mostrar Widget", 0, QApplication::UnicodeUTF8));
        menuArchivo->setTitle(QApplication::translate("FTMClass", "Archivo", 0, QApplication::UnicodeUTF8));
        menuEditar->setTitle(QApplication::translate("FTMClass", "Editar", 0, QApplication::UnicodeUTF8));
        menuBox->setTitle(QApplication::translate("FTMClass", "Box", 0, QApplication::UnicodeUTF8));
        menuFTM->setTitle(QApplication::translate("FTMClass", "FTM", 0, QApplication::UnicodeUTF8));
        menuFiltros->setTitle(QApplication::translate("FTMClass", "Filtros", 0, QApplication::UnicodeUTF8));
        menuTipo_Seg_Der->setTitle(QApplication::translate("FTMClass", "Tipo Seg. Der.", 0, QApplication::UnicodeUTF8));
        menuVolumen->setTitle(QApplication::translate("FTMClass", "Volumen", 0, QApplication::UnicodeUTF8));
        menuIluminaci_n->setTitle(QApplication::translate("FTMClass", "Iluminaci\303\263n", 0, QApplication::UnicodeUTF8));
        menuFT_Uni->setTitle(QApplication::translate("FTMClass", "FT Uni", 0, QApplication::UnicodeUTF8));
        statusBar->setStyleSheet(QApplication::translate("FTMClass", "border-top-color: rgb(62, 62, 62);", 0, QApplication::UnicodeUTF8));
        ConFigClasi->setTitle(QApplication::translate("FTMClass", "Conf. Fig.", 0, QApplication::UnicodeUTF8));
        pColorConf1->setText(QApplication::translate("FTMClass", "C1", 0, QApplication::UnicodeUTF8));
        pColorConf2->setText(QApplication::translate("FTMClass", "C2", 0, QApplication::UnicodeUTF8));
        groupBox->setTitle(QApplication::translate("FTMClass", "Lista Fig.", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem = tablaFigClasi->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QApplication::translate("FTMClass", "Figura", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem1 = tablaFigClasi->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QApplication::translate("FTMClass", "Nombre", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem2 = tablaFigClasi->horizontalHeaderItem(2);
        ___qtablewidgetitem2->setText(QApplication::translate("FTMClass", "Estado", 0, QApplication::UnicodeUTF8));
        crearFigClasi->setText(QString());
        eliminarFigClasi->setText(QString());
        subirFigClasi->setText(QString());
        bajarFigClasi->setText(QString());
        refrescarVol->setText(QString());
        AutoRefresh->setText(QApplication::translate("FTMClass", "Auto-refrescar", 0, QApplication::UnicodeUTF8));
        groupBox_2->setTitle(QApplication::translate("FTMClass", " FT Multidimensional", 0, QApplication::UnicodeUTF8));
        cero->setText(QApplication::translate("FTMClass", "0", 0, QApplication::UnicodeUTF8));
        cero_2->setText(QApplication::translate("FTMClass", "0", 0, QApplication::UnicodeUTF8));
        Push1D->setText(QApplication::translate("FTMClass", "1D", 0, QApplication::UnicodeUTF8));
        Push2D->setText(QApplication::translate("FTMClass", "2D", 0, QApplication::UnicodeUTF8));
        Push3D->setText(QApplication::translate("FTMClass", "3D", 0, QApplication::UnicodeUTF8));
        calculaKernels->setText(QApplication::translate("FTMClass", "Calcular", 0, QApplication::UnicodeUTF8));
        groupSegunda->setTitle(QApplication::translate("FTMClass", "f\302\264\302\264", 0, QApplication::UnicodeUTF8));

        const bool __sortingEnabled = listSegunda->isSortingEnabled();
        listSegunda->setSortingEnabled(false);
        QListWidgetItem *___qlistwidgetitem = listSegunda->item(0);
        ___qlistwidgetitem->setText(QApplication::translate("FTMClass", "-0.140", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem1 = listSegunda->item(1);
        ___qlistwidgetitem1->setText(QApplication::translate("FTMClass", "0.812", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem2 = listSegunda->item(2);
        ___qlistwidgetitem2->setText(QApplication::translate("FTMClass", "0.593", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem3 = listSegunda->item(3);
        ___qlistwidgetitem3->setText(QApplication::translate("FTMClass", "-2.5", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem4 = listSegunda->item(4);
        ___qlistwidgetitem4->setText(QApplication::translate("FTMClass", "0.593", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem5 = listSegunda->item(5);
        ___qlistwidgetitem5->setText(QApplication::translate("FTMClass", "0.812", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem6 = listSegunda->item(6);
        ___qlistwidgetitem6->setText(QApplication::translate("FTMClass", "-0.140", 0, QApplication::UnicodeUTF8));
        listSegunda->setSortingEnabled(__sortingEnabled);

        groupPrimera->setTitle(QApplication::translate("FTMClass", "f\302\264", 0, QApplication::UnicodeUTF8));

        const bool __sortingEnabled1 = listPrimera->isSortingEnabled();
        listPrimera->setSortingEnabled(false);
        QListWidgetItem *___qlistwidgetitem7 = listPrimera->item(0);
        ___qlistwidgetitem7->setText(QApplication::translate("FTMClass", "0.125", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem8 = listPrimera->item(1);
        ___qlistwidgetitem8->setText(QApplication::translate("FTMClass", "0.500", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem9 = listPrimera->item(2);
        ___qlistwidgetitem9->setText(QApplication::translate("FTMClass", "0.625", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem10 = listPrimera->item(3);
        ___qlistwidgetitem10->setText(QApplication::translate("FTMClass", "0", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem11 = listPrimera->item(4);
        ___qlistwidgetitem11->setText(QApplication::translate("FTMClass", "-0.625", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem12 = listPrimera->item(5);
        ___qlistwidgetitem12->setText(QApplication::translate("FTMClass", "-0.500", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem13 = listPrimera->item(6);
        ___qlistwidgetitem13->setText(QApplication::translate("FTMClass", "-0.125", 0, QApplication::UnicodeUTF8));
        listPrimera->setSortingEnabled(__sortingEnabled1);

        groupInterpola->setTitle(QApplication::translate("FTMClass", "f", 0, QApplication::UnicodeUTF8));

        const bool __sortingEnabled2 = listInterpola->isSortingEnabled();
        listInterpola->setSortingEnabled(false);
        QListWidgetItem *___qlistwidgetitem14 = listInterpola->item(0);
        ___qlistwidgetitem14->setText(QApplication::translate("FTMClass", "0.062", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem15 = listInterpola->item(1);
        ___qlistwidgetitem15->setText(QApplication::translate("FTMClass", "0.250", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem16 = listInterpola->item(2);
        ___qlistwidgetitem16->setText(QApplication::translate("FTMClass", "0.437", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem17 = listInterpola->item(3);
        ___qlistwidgetitem17->setText(QApplication::translate("FTMClass", "0.5", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem18 = listInterpola->item(4);
        ___qlistwidgetitem18->setText(QApplication::translate("FTMClass", "0.437", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem19 = listInterpola->item(5);
        ___qlistwidgetitem19->setText(QApplication::translate("FTMClass", "0.250", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem20 = listInterpola->item(6);
        ___qlistwidgetitem20->setText(QApplication::translate("FTMClass", "0.062", 0, QApplication::UnicodeUTF8));
        listInterpola->setSortingEnabled(__sortingEnabled2);

        label->setText(QApplication::translate("FTMClass", "Tama\303\261o:", 0, QApplication::UnicodeUTF8));
        groupBoxUni->setTitle(QApplication::translate("FTMClass", "FT Unidimensional", 0, QApplication::UnicodeUTF8));
        Push1DFTUni->setText(QApplication::translate("FTMClass", "1D", 0, QApplication::UnicodeUTF8));
        Push2Do3DFTUni->setText(QApplication::translate("FTMClass", "2D|3D", 0, QApplication::UnicodeUTF8));
        groupBoxVol->setTitle(QApplication::translate("FTMClass", "Editar Vol\303\272men", 0, QApplication::UnicodeUTF8));
        labelTamVoxel->setText(QApplication::translate("FTMClass", "Valor del  V\303\263xel:", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("FTMClass", "Min X:", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("FTMClass", "Min Y:", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("FTMClass", "Min Z:", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("FTMClass", "Max X:", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("FTMClass", "Max Y:", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("FTMClass", "Max Z:", 0, QApplication::UnicodeUTF8));
        labelMuestreo->setText(QApplication::translate("FTMClass", " Muestreo del rayo:", 0, QApplication::UnicodeUTF8));
        lineEditValor->setText(QApplication::translate("FTMClass", "0.00001", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("FTMClass", "Escalar Vol\303\272men", 0, QApplication::UnicodeUTF8));
        x->setText(QApplication::translate("FTMClass", "X", 0, QApplication::UnicodeUTF8));
        y->setText(QApplication::translate("FTMClass", "Y", 0, QApplication::UnicodeUTF8));
        z->setText(QApplication::translate("FTMClass", "Z", 0, QApplication::UnicodeUTF8));
        groupBoxFTMWidget->setTitle(QApplication::translate("FTMClass", "FTM Histograma 2D", 0, QApplication::UnicodeUTF8));
        labelActualValorHistoFTM->setText(QApplication::translate("FTMClass", "Nro Actual:", 0, QApplication::UnicodeUTF8));
        groupIlumina->setTitle(QApplication::translate("FTMClass", "Iluminaci\303\263n", 0, QApplication::UnicodeUTF8));
        radioGradiente->setText(QApplication::translate("FTMClass", "Mag. del Gradiente", 0, QApplication::UnicodeUTF8));
        radioSegDerivada->setText(QApplication::translate("FTMClass", "Seg. Derivada", 0, QApplication::UnicodeUTF8));
        radioMagYSeg->setText(QApplication::translate("FTMClass", "Mag. del Grad. y Seg. Der.", 0, QApplication::UnicodeUTF8));
        radioBlinnPhong->setText(QApplication::translate("FTMClass", "Blinn\342\200\223Phong", 0, QApplication::UnicodeUTF8));
        Lambiental->setText(QApplication::translate("FTMClass", "Ambiental", 0, QApplication::UnicodeUTF8));
        Ldifusa->setText(QApplication::translate("FTMClass", "Difusa", 0, QApplication::UnicodeUTF8));
        Lespecular->setText(QApplication::translate("FTMClass", "Especular", 0, QApplication::UnicodeUTF8));
        pushAmbiental->setText(QApplication::translate("FTMClass", "...", 0, QApplication::UnicodeUTF8));
        pushDifusa->setText(QApplication::translate("FTMClass", "...", 0, QApplication::UnicodeUTF8));
        pushEspecular->setText(QApplication::translate("FTMClass", "...", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("FTMClass", "Exp. Refl. Especular:", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class FTMClass: public Ui_FTMClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_FTM_H
